# Generated by Django 3.0.6 on 2020-05-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('sw_langauges', models.CharField(max_length=100)),
                ('schooling', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=1000)),
            ],
        ),
    ]
