# Generated by Django 3.0.6 on 2020-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0002_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='pic',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
