# Generated by Django 3.0.6 on 2020-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0003_auto_20200529_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='pic',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='pic',
            field=models.ImageField(default='', upload_to='gallery'),
        ),
    ]
