# Generated by Django 3.0.6 on 2020-06-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0004_auto_20200529_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='resume',
            field=models.FileField(default='', upload_to='documents'),
            preserve_default=False,
        ),
    ]
