# Generated by Django 3.0.7 on 2020-06-18 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0005_aboutme_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showcaseitem',
            old_name='url',
            new_name='path_to',
        ),
    ]
