# Generated by Django 3.0.7 on 2020-06-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0006_auto_20200618_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcaseitem',
            name='path_to',
        ),
    ]
