# Generated by Django 3.0.7 on 2020-06-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0007_remove_showcaseitem_path_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcaseitem',
            name='path_to',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
