# Generated by Django 3.0.7 on 2020-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0009_auto_20200618_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showcaseitem',
            name='path_to_git',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='showcaseitem',
            name='path_to_site',
            field=models.URLField(blank=True),
        ),
    ]
