# Generated by Django 3.0.7 on 2020-06-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_showcase', '0010_auto_20200618_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='contact',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
